name: "Update news table and dashboard"

on:

  schedule:
    - cron:  '0 */4 * * *'


jobs:
  update-spread:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update sheet
      env:
        GSPREAD_PRIVATE_KEY: ${{ secrets.GS_PRIVATE_KEY }}
      run: |
        python cikk_getter.py
    - name: Update Dashboard
      env:
        GSPREAD_PRIVATE_KEY: ${{ secrets.GS_PRIVATE_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python make_dashboard.py
        git config --global user.email "gh-actions@github.com"
        git config --global user.name "github actions"
        git add docs
        git commit --message "github actions dashboard build"
        git remote add origin-pages https://${GH_TOKEN}@github.com/endremborza/cikk-getter.git > /dev/null 2>&1
        git push --quiet origin-pages HEAD:master

